"""Public command-boundary canaries for the portable manifest runner."""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

from cargo_test_manifest import GateError


CHECKER = Path(__file__).resolve().parents[1] / "check-portable-test-manifest"


def write_fixture(root: Path, relative: str, text: str) -> None:
    """Write one temporary Cargo fixture."""

    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def fixture_manifest(test_name: str) -> str:
    """Return a strict one-target manifest for the fixture."""

    value = {
        "schema_version": 1,
        "targets": [
            {
                "features": [],
                "package": "greenlit-app",
                "selector": "test",
                "target": "behavior",
                "test_cfgs": ["litci_test_boundaries"],
                "tests": [test_name],
            }
        ],
    }
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def boundary_run(
    root: Path,
    manifest: Path,
    *,
    execute: bool,
) -> subprocess.CompletedProcess[str]:
    """Invoke the public runner with an empty encoded-flags environment."""

    command = [
        sys.executable,
        str(CHECKER),
        "--repository-root",
        str(root),
        "--manifest",
        str(manifest),
    ]
    if execute:
        command.append("--run")
    environment = os.environ.copy()
    environment["CARGO_ENCODED_RUSTFLAGS"] = ""
    return subprocess.run(
        command,
        check=False,
        capture_output=True,
        env=environment,
        text=True,
    )


def create_fixture(root: Path) -> tuple[Path, Path]:
    """Create a locked custom-path integration-test workspace."""

    write_fixture(
        root,
        "Cargo.toml",
        '[workspace]\nresolver = "2"\nmembers = ["demo"]\n',
    )
    write_fixture(
        root,
        "Cargo.lock",
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 4\n\n[[package]]\nname = \"greenlit-app\"\n"
        "version = \"0.1.0\"\n",
    )
    write_fixture(
        root,
        "demo/Cargo.toml",
        "[package]\nname = \"greenlit-app\"\nversion = \"0.1.0\"\n"
        "edition = \"2024\"\n"
        "[[test]]\nname = \"behavior\"\npath = \"acceptance/behavior.rs\"\n",
    )
    write_fixture(root, "demo/src/lib.rs", "pub fn value() -> bool { true }\n")
    test = root / "demo/acceptance/behavior.rs"
    manifest = root / "portable.json"
    write_fixture(
        root,
        "demo/acceptance/behavior.rs",
        "#[cfg(not(litci_test_boundaries))]\n"
        "compile_error!(\"test boundary cfg is absent\");\n"
        "#[test]\nfn works() { assert!(greenlit_app::value()); }\n",
    )
    manifest.write_text(fixture_manifest("works"), encoding="utf-8")
    return test, manifest


def require_failure(
    result: subprocess.CompletedProcess[str],
    expected: str,
    label: str,
) -> None:
    """Require one public command to fail with its authority diagnostic."""

    if result.returncode != 1 or expected not in result.stderr:
        raise GateError(
            f"{label} canary did not fail\n{result.stdout}{result.stderr}"
        )


def self_test_negative() -> int:
    """Exercise exact-target, exact-case, custom-path, and run boundaries."""

    with tempfile.TemporaryDirectory(prefix="greenlit-portable-manifest-") as directory:
        root = Path(directory)
        test, manifest = create_fixture(root)

        baseline = boundary_run(root, manifest, execute=False)
        if baseline.returncode != 0:
            raise GateError(
                "portable clean command-boundary canary failed\n"
                f"{baseline.stdout}{baseline.stderr}"
            )

        manifest.write_text(fixture_manifest("missing"), encoding="utf-8")
        require_failure(
            boundary_run(root, manifest, execute=False),
            "selected tests differ",
            "portable exact-case",
        )

        manifest.write_text(fixture_manifest("works"), encoding="utf-8")
        test.write_text(
            "#[cfg(not(litci_test_boundaries))]\n"
            "compile_error!(\"test boundary cfg is absent\");\n"
            "#[test]\nfn works() { assert!(greenlit_app::value()); }\n"
            "#[test]\nfn added() { assert!(greenlit_app::value()); }\n",
            encoding="utf-8",
        )
        require_failure(
            boundary_run(root, manifest, execute=False),
            "selected tests differ",
            "portable unexpected-case",
        )

        test.write_text("pub fn no_test_case() {}\n", encoding="utf-8")
        require_failure(
            boundary_run(root, manifest, execute=False),
            "portable Cargo commands selected zero tests",
            "portable zero-selection",
        )

        cargo_manifest = root / "demo/Cargo.toml"
        baseline_cargo = cargo_manifest.read_text(encoding="utf-8")
        cargo_manifest.write_text(
            baseline_cargo
            + "[[test]]\nname = \"extra\"\npath = \"acceptance/extra.rs\"\n",
            encoding="utf-8",
        )
        write_fixture(
            root,
            "demo/acceptance/extra.rs",
            "#[test]\nfn newly_selected_target() { assert!(true); }\n",
        )
        require_failure(
            boundary_run(root, manifest, execute=False),
            "portable nonzero targets differ",
            "portable custom-target",
        )
        cargo_manifest.write_text(baseline_cargo, encoding="utf-8")

        test.write_text("#[test]\nfn works() { assert!(false); }\n", encoding="utf-8")
        execution = boundary_run(root, manifest, execute=True)
        if execution.returncode != 1 or "test failed" not in (
            execution.stdout + execution.stderr
        ):
            raise GateError(
                "portable failing-run canary did not fail\n"
                f"{execution.stdout}{execution.stderr}"
            )
    print(
        "portable test manifest negative gate passed: custom path, exact case, "
        "case/target addition, zero-selection, and failing execution canaries"
    )
    return 0
