"""Public command-boundary canaries for the test-authority gate."""

from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

from .model import GateError


CHECKER = Path(__file__).resolve().parents[1] / "check-test-authority"


def write_fixture(root: Path, relative: str, text: str) -> None:
    """Write one temporary self-test fixture."""

    path = root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def boundary_run(root: Path) -> subprocess.CompletedProcess[str]:
    """Invoke the installed public checker against one fixture repository."""

    command = [
        sys.executable,
        "-B",
        str(CHECKER),
        "--repository-root",
        str(root),
    ]
    try:
        return subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
        )
    except OSError as error:
        raise GateError(f"could not execute command-boundary canary: {error}") from error


def clean_fixture() -> dict[str, str]:
    """Return a locked two-package workspace accepted by the authority gate."""

    return {
        "Cargo.toml": (
            '[workspace]\nresolver = "2"\n'
            'members = ["crates/greenlit-expr", "crates/demo"]\n'
        ),
        "Cargo.lock": (
            "# This file is automatically @generated by Cargo.\n"
            "# It is not intended for manual editing.\n"
            "version = 4\n\n"
            "[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n\n"
            "[[package]]\nname = \"greenlit-expr\"\nversion = \"0.1.0\"\n"
        ),
        ".github/workflows/release.yml": (
            "jobs:\n  verify:\n    steps:\n"
            "      - run: cargo build --locked --release\n"
        ),
        "tools/release-check": "cargo build --locked --release\n",
        "crates/greenlit-expr/Cargo.toml": (
            "[package]\nname = \"greenlit-expr\"\nversion = \"0.1.0\"\n"
            "edition = \"2024\"\n"
        ),
        "crates/greenlit-expr/src/lib.rs": (
            "#[cfg(test)] mod oracle_tests { #[test] fn documented_rule() {} }\n"
        ),
        "crates/demo/Cargo.toml": (
            "[package]\nname = \"demo\"\nversion = \"0.1.0\"\nedition = \"2024\"\n"
            "[features]\nlive = []\n"
            "[[test]]\nname = \"capability\"\n"
            "path = \"acceptance/capability.rs\"\n"
            "required-features = [\"live\"]\n"
        ),
        "crates/demo/src/lib.rs": "pub fn production() {}\n",
        "crates/demo/tests/detection.rs": (
            "struct FakeProber;\n#[test]\nfn external_prober_boundary() {"
            " assert!(true); }\n"
        ),
        "crates/demo/acceptance/capability.rs": (
            "#[test]\nfn live_boundary() { assert!(true); }\n"
        ),
    }


def rejection_mutations() -> list[tuple[dict[str, str], str]]:
    """Return every mutation and the public diagnostic it must trigger."""

    return [
        (
            {
                "crates/demo/src/lib.rs": (
                    "#[cfg(test)] mod tests { #[test] fn helper() {} }\n"
                )
            },
            "source-local test code",
        ),
        (
            {
                "crates/demo/src/lib.rs": (
                    "#[cfg(all(target_os = \"linux\", test))]\n"
                    "mod hidden_tests { #[test] fn helper() {} }\n"
                )
            },
            "source-local test code",
        ),
        (
            {
                "crates/demo/acceptance/capability.rs": (
                    "struct RecordingEngine;\n"
                    "#[test] fn substituted() { assert!(true); }\n"
                )
            },
            "own-crate runtime substitute",
        ),
        (
            {
                "crates/demo/acceptance/capability.rs": (
                    "#[test]\n#[ignore]\nfn ignored_capability() {}\n"
                )
            },
            "ignored test",
        ),
        (
            {
                "crates/demo/acceptance/capability.rs": (
                    "#[test]\nfn absent_capability() { "
                    "if unavailable() { return } assert!(true); }\n"
                )
            },
            "capability self-skip",
        ),
        (
            {
                "crates/demo/tests/detection.rs": (
                    "#[cfg(feature = \"live\")]\n"
                    "#[test]\nfn hidden_capability() { assert!(true); }\n"
                )
            },
            "inline feature-gated test",
        ),
        (
            {
                "crates/demo/examples/private.rs": (
                    "#[test]\nfn helper_behavior() { assert!(true); }\n"
                    "fn main() {}\n"
                )
            },
            "source-local test code",
        ),
        (
            {
                "crates/demo/build.rs": (
                    "#[test]\nfn helper_behavior() { assert!(true); }\n"
                    "fn main() {}\n"
                )
            },
            "source-local test code",
        ),
        (
            {
                "crates/demo/tests/orphan/private.rs": (
                    "#[test]\nfn never_selected() { assert!(true); }\n"
                )
            },
            "unselected test code",
        ),
        (
            {
                "tools/release-check": (
                    "RUSTFLAGS='--cfg litci_test_boundaries' "
                    "cargo build --locked --release\n"
                )
            },
            "release test cfg",
        ),
    ]


def self_test_negative() -> int:
    """Exercise the clean baseline and every rejection at the public boundary."""

    clean = clean_fixture()
    mutations = rejection_mutations()
    with tempfile.TemporaryDirectory(prefix="greenlit-test-authority-") as directory:
        baseline = Path(directory) / "baseline"
        for relative, text in clean.items():
            write_fixture(baseline, relative, text)
        positive = boundary_run(baseline)
        if positive.returncode != 0:
            raise GateError(
                "clean command-boundary canary failed\n"
                f"{positive.stdout}{positive.stderr}"
            )

        for index, (changed, expected) in enumerate(mutations):
            case = Path(directory) / f"negative-{index}"
            for clean_relative, clean_text in clean.items():
                write_fixture(case, clean_relative, clean_text)
            for relative, text in changed.items():
                write_fixture(case, relative, text)
            result = boundary_run(case)
            if result.returncode != 1 or expected not in result.stderr:
                raise GateError(
                    f"{expected} canary did not fail at the public command boundary\n"
                    f"status={result.returncode}\n{result.stdout}{result.stderr}"
                )
    print(
        f"test authority negative gate passed: clean baseline and "
        f"{len(mutations)} rejection canaries"
    )
    return 0
