//! `strategy.matrix`/`include`/`exclude`/`fail-fast`/`max-parallel` →
//! [`StrategyPlan`]: the four-phase matrix expansion algorithm.
//!
//! The ordering and `include`/`exclude` rules follow
//! [Running variations of jobs in a workflow](https://docs.github.com/en/actions/how-tos/write-workflows/choose-what-workflows-do/run-job-variations)
//! and the `strategy.matrix` section of the
//! [workflow syntax reference](https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstrategymatrix).

mod algorithm;
mod deferred;
mod expand;
mod strategy;

pub use deferred::DeferredMatrixExpression;
pub(crate) use strategy::plan_strategy;
pub use strategy::{
    MatrixPlan, StrategyControl, StrategyPlan, materialize_controls, materialize_matrix,
};

use greenlit_expr::Value;
use indexmap::IndexMap;
use serde::ser::SerializeStruct;
use std::borrow::Borrow;
use std::sync::Arc;

use greenlit_workflow::Span;

use crate::defer::DeferReason;
use crate::partial_eval::PartialEvalError;

/// Default (and v0-only) cap on how many legs one matrix may expand to.
///
/// GitHub documents a maximum of 256 jobs generated by a matrix.
/// <https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#jobsjob_idstrategymatrix>
pub const DEFAULT_MAX_MATRIX_LEGS: usize = 256;

/// One expanded matrix combination.
#[derive(Debug, Clone, PartialEq, serde::Serialize)]
pub struct MatrixLeg {
    /// Stable ordinal within the job (final leg list order).
    pub index: usize,
    /// This leg's `axis: value` pairs, in key declaration order.
    pub values: IndexMap<MatrixKey, MatrixValue>,
    /// Where this leg came from.
    pub origin: LegOrigin,
}

/// An interned matrix property name.
///
/// Matrix expansion repeats every axis name in as many as 256 concrete
/// legs. Sharing the immutable string keeps that repository-controlled
/// multiplication bounded while serializing exactly like the original JSON
/// object key.
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub struct MatrixKey(Arc<str>);

impl MatrixKey {
    /// Returns the property name as text.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Borrow<str> for MatrixKey {
    fn borrow(&self) -> &str {
        self.as_str()
    }
}

impl From<String> for MatrixKey {
    fn from(value: String) -> Self {
        Self(value.into())
    }
}

impl From<&str> for MatrixKey {
    fn from(value: &str) -> Self {
        Self(value.into())
    }
}

impl serde::Serialize for MatrixKey {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

impl MatrixLeg {
    /// GHA-style display name: `job-name (v1, v2, …)` joining the leg's
    /// values in matrix declaration order.
    #[must_use]
    pub fn display_suffix(&self) -> String {
        if self.values.is_empty() {
            return String::new();
        }
        let joined = self
            .values
            .values()
            .map(MatrixValue::display)
            .collect::<Vec<_>>()
            .join(", ");
        format!(" ({joined})")
    }
}

/// Where a [`MatrixLeg`] came from.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize)]
#[serde(tag = "kind", rename_all = "kebab-case")]
pub enum LegOrigin {
    /// A surviving cartesian-product combination.
    Product,
    /// Created because `include` entry `entry_index` (0-based, list order)
    /// did not fit any surviving product combination.
    Include {
        /// The include entry's index.
        entry_index: usize,
    },
}

/// A deep-equality-comparable mirror of a matrix axis/`include`/`exclude`
/// value. GitHub permits object values here, addressed as
/// `matrix.key.subkey`.
///
/// Stable plan JSON uses a tagged representation for every variant:
/// `{ "kind": "null" }` or `{ "kind": "...", "value": ... }`.
/// Tagging keeps JSON strings, mappings, and non-finite numbers
/// unambiguous. Finite numbers use a JSON number; `NaN`, positive infinity,
/// and negative infinity use those canonical strings inside the tagged
/// number value because JSON has no native non-finite numeric literals.
#[derive(Debug, Clone, PartialEq)]
pub enum MatrixValue {
    /// `null`.
    Null,
    /// `true`/`false`.
    Bool(bool),
    /// A number.
    Number(f64),
    /// A string.
    String(Arc<str>),
    /// A sequence.
    Sequence(Arc<[MatrixValue]>),
    /// A mapping, insertion-ordered.
    Mapping(Arc<IndexMap<String, MatrixValue>>),
}

impl serde::Serialize for MatrixValue {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        let mut value = serializer.serialize_struct(
            "MatrixValue",
            if matches!(self, Self::Null) { 1 } else { 2 },
        )?;
        match self {
            Self::Null => value.serialize_field("kind", "null")?,
            Self::Bool(boolean) => {
                value.serialize_field("kind", "boolean")?;
                value.serialize_field("value", boolean)?;
            }
            Self::Number(number) => {
                value.serialize_field("kind", "number")?;
                value.serialize_field("value", &SerializableMatrixNumber(*number))?;
            }
            Self::String(string) => {
                value.serialize_field("kind", "string")?;
                value.serialize_field("value", string.as_ref())?;
            }
            Self::Sequence(sequence) => {
                value.serialize_field("kind", "sequence")?;
                value.serialize_field("value", sequence.as_ref())?;
            }
            Self::Mapping(mapping) => {
                value.serialize_field("kind", "mapping")?;
                value.serialize_field("value", mapping.as_ref())?;
            }
        }
        value.end()
    }
}

struct SerializableMatrixNumber(f64);

impl serde::Serialize for SerializableMatrixNumber {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        if self.0.is_nan() {
            serializer.serialize_str("NaN")
        } else if self.0 == f64::INFINITY {
            serializer.serialize_str("Infinity")
        } else if self.0 == f64::NEG_INFINITY {
            serializer.serialize_str("-Infinity")
        } else {
            serializer.serialize_f64(self.0)
        }
    }
}

impl MatrixValue {
    /// Renders a value for [`MatrixLeg::display_suffix`] — a short,
    /// human-readable token, not a data-preserving serialization.
    fn display(&self) -> String {
        match self {
            MatrixValue::Null => "null".to_string(),
            MatrixValue::Bool(b) => b.to_string(),
            MatrixValue::Number(n) => greenlit_expr::value::format_g15(*n),
            MatrixValue::String(s) => s.to_string(),
            MatrixValue::Sequence(_) => "[…]".to_string(),
            MatrixValue::Mapping(_) => "{…}".to_string(),
        }
    }
}

/// Everything that can go wrong expanding a `strategy:` block.
#[derive(Debug, thiserror::Error)]
pub enum MatrixError {
    /// `exclude:` had an entry with no keys at all — this would vacuously
    /// match (and remove) every combination.
    #[error("{span}: an `exclude` entry must name at least one matrix key")]
    EmptyExcludeEntry {
        /// The empty entry's span.
        span: Span,
    },
    /// The expanded leg count exceeds the cap.
    #[error("{span}: matrix expands to {count} jobs, exceeding the limit of {cap}")]
    TooManyLegs {
        /// How many legs were produced.
        count: usize,
        /// The configured cap.
        cap: usize,
        /// The `strategy.matrix` span.
        span: Span,
    },
    /// Computing the cartesian-product cardinality overflowed `usize`.
    /// This is rejected before allocating the product.
    #[error(
        "{span}: matrix cardinality is too large to represent and exceeds the limit of {cap} jobs"
    )]
    CardinalityOverflow {
        /// The configured cap.
        cap: usize,
        /// The `strategy.matrix` span.
        span: Span,
    },
    /// A low-level expansion call received a matrix value that still
    /// referenced runtime-only data. Normal planning detects this first and
    /// emits [`MatrixPlan::Deferred`]; this error keeps the expansion layer
    /// total if it is reused with unresolved input.
    #[error(
        "{span}: matrix value depends on data not available at plan time (needs {defers_on:?})"
    )]
    ValueNotStatic {
        /// Where the offending value appears.
        span: Span,
        /// Why it could not be resolved now.
        defers_on: Vec<DeferReason>,
    },
    /// `strategy.matrix: ${{ ... }}` evaluated to a non-object value.
    #[error("{span}: strategy.matrix expression must evaluate to an object")]
    ExpressionNotMatrixShaped {
        /// The expression's span.
        span: Span,
    },
    /// An axis or `include`/`exclude` field in an expression-produced
    /// matrix was not an array.
    #[error(
        "{span}: strategy.matrix expression field '{field}' must evaluate to an array, got {actual}"
    )]
    ExpressionFieldNotArray {
        /// The expression object's field name.
        field: String,
        /// The actual expression value kind.
        actual: &'static str,
        /// The enclosing expression's span. Evaluated object members have
        /// no finer-grained source spans.
        span: Span,
    },
    /// An `include`/`exclude` array item in an expression-produced matrix
    /// was not an object.
    #[error("{span}: strategy.matrix.{field}[{index}] must evaluate to an object, got {actual}")]
    ExpressionEntryNotObject {
        /// Either `include` or `exclude`.
        field: &'static str,
        /// Zero-based entry index.
        index: usize,
        /// The actual expression value kind.
        actual: &'static str,
        /// The enclosing expression's span. Evaluated array items have no
        /// finer-grained source spans.
        span: Span,
    },
    /// `strategy.fail-fast` resolved to a non-boolean value.
    #[error("{span}: strategy.fail-fast must evaluate to a boolean, got {actual}")]
    InvalidFailFastType {
        /// The actual expression value kind.
        actual: &'static str,
        /// The field's span.
        span: Span,
    },
    /// `strategy.max-parallel` resolved to a non-number value.
    #[error("{span}: strategy.max-parallel must evaluate to a number, got {actual}")]
    InvalidMaxParallelType {
        /// The actual expression value kind.
        actual: &'static str,
        /// The field's span.
        span: Span,
    },
    /// `strategy.max-parallel` resolved to a number that cannot represent
    /// the positive integral concurrency carried by [`StrategyPlan`].
    #[error(
        "{span}: strategy.max-parallel must be a positive integer no greater than {}, got {value}",
        u32::MAX
    )]
    InvalidMaxParallelValue {
        /// The invalid numeric value.
        value: f64,
        /// The field's span.
        span: Span,
    },
    /// An embedded expression failed to parse or evaluate.
    #[error("{span}: {source}")]
    PartialEval {
        /// Where the offending value appears.
        span: Span,
        /// The underlying failure.
        #[source]
        source: PartialEvalError,
    },
}

pub(super) fn value_kind_name(value: &Value) -> &'static str {
    match value {
        Value::Null => "null",
        Value::Bool(_) => "boolean",
        Value::Number(_) => "number",
        Value::String(_) => "string",
        Value::Array(_) => "array",
        Value::Object(_) => "object",
    }
}

/// A matrix axis/`include`/`exclude` entry, already folded to
/// [`MatrixValue`] — the shape [`expand`]'s algorithm operates on,
/// independent of whether it came from an inline `strategy.matrix:`
/// mapping or a `${{ fromJSON(...) }}` expression's resulting object.
pub(crate) type ResolvedEntry = Vec<(String, MatrixValue)>;
